### ISSUE TITLE
[Feature] Use single precision by default

### ISSUE THREAD

**Issue by RolandMacDoland** [pasqal-io/horqrux#18]
@dominikandreasseitz If you could add a description.

**Comment by RolandMacDoland** [comment]
> It seems this issue comes from Jax not supporting creating complex128 arrays:
> 
> ```
> UserWarning: Explicitly requested dtype <class
>            'jax.numpy.complex128'> requested in array is not available, and will
>            be truncated to dtype complex64. To enable more dtypes, set the
>            jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell
>            environment variable.
> ```

Ah well...

**Comment by chMoussa** [comment]
@RolandMacDoland Unless we manage to set `jax_enable_x64` configuration variable at startup as it is specified in the [doc](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision).
